### ISSUE TITLE
`write_npy` fails on Windows

### ISSUE THREAD

**Issue by kgord831** [HunterBelanger/exdir-cpp#1]
In [`write_npy`](https://github.com/HunterBelanger/exdir-cpp/blob/master/include/exdir/ndarray.hpp#L987), open the file stream in binary mode. This is needed on Windows which, by default, [will convert `\n` into `\r\n`](https://en.cppreference.com/w/cpp/io/c/FILE#Binary_and_text_modes). Specifying `std::ios::binary` for the open mode will ensure that Windows will not make this replacement.

Inside [`write_npy`](https://github.com/HunterBelanger/exdir-cpp/blob/master/include/exdir/ndarray.hpp#L987), replace
```cpp
std::ofstream file(fname);
```

with
```cpp
std::ofstream file(fname, std::ios::binary);
```

Tested with Visual Studio 2015 on Windows. This should have no impact on Linux (I didn't test this).

**Comment by HunterBelanger** [comment]
Thank you for pointing this out. I have another repo which contained just the `NDArray` class where this bug was updated, but I never did it here. I just added a commit to use FetchContent to pull that other updated repo at build, so that an up to date NDArray class will always be used. I also made a few other small changes for building on Windows. I tested with MSVC 19 and it seemed to build fine now and run. If you still have problems, feel free to reopen this.
